name: HotMessages
version: 1.0.0
main: ru.sitbix.hotmessages.HotMessagesPlugin
api-version: '1.21.11'
folia-supported: true
author: Sitbix
description: Advanced Folia-ready chat filter with logs, GUI, whitelist and blacklist.

permissions:
  hotmessages.admin:
    description: Full access to HotMessages commands and GUI.
    default: op
  hotmessages.notify:
    description: Receives alerts when a message is blocked.
    default: op
  hotmessages.bypass:
    description: Bypasses all filters.
    default: false
  hotmessages.ghost:
    description: Can use /hm ghost to see private messages.
    default: op
